require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PasteventsController do

  # This should return the minimal set of attributes required to create a valid
  # Pastevent. As you add validations to Pastevent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PasteventsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pastevents as @pastevents" do
      pastevent = Pastevent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pastevents).should eq([pastevent])
    end
  end

  describe "GET show" do
    it "assigns the requested pastevent as @pastevent" do
      pastevent = Pastevent.create! valid_attributes
      get :show, {:id => pastevent.to_param}, valid_session
      assigns(:pastevent).should eq(pastevent)
    end
  end

  describe "GET new" do
    it "assigns a new pastevent as @pastevent" do
      get :new, {}, valid_session
      assigns(:pastevent).should be_a_new(Pastevent)
    end
  end

  describe "GET edit" do
    it "assigns the requested pastevent as @pastevent" do
      pastevent = Pastevent.create! valid_attributes
      get :edit, {:id => pastevent.to_param}, valid_session
      assigns(:pastevent).should eq(pastevent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pastevent" do
        expect {
          post :create, {:pastevent => valid_attributes}, valid_session
        }.to change(Pastevent, :count).by(1)
      end

      it "assigns a newly created pastevent as @pastevent" do
        post :create, {:pastevent => valid_attributes}, valid_session
        assigns(:pastevent).should be_a(Pastevent)
        assigns(:pastevent).should be_persisted
      end

      it "redirects to the created pastevent" do
        post :create, {:pastevent => valid_attributes}, valid_session
        response.should redirect_to(Pastevent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pastevent as @pastevent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pastevent.any_instance.stub(:save).and_return(false)
        post :create, {:pastevent => {}}, valid_session
        assigns(:pastevent).should be_a_new(Pastevent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pastevent.any_instance.stub(:save).and_return(false)
        post :create, {:pastevent => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pastevent" do
        pastevent = Pastevent.create! valid_attributes
        # Assuming there are no other pastevents in the database, this
        # specifies that the Pastevent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pastevent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => pastevent.to_param, :pastevent => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested pastevent as @pastevent" do
        pastevent = Pastevent.create! valid_attributes
        put :update, {:id => pastevent.to_param, :pastevent => valid_attributes}, valid_session
        assigns(:pastevent).should eq(pastevent)
      end

      it "redirects to the pastevent" do
        pastevent = Pastevent.create! valid_attributes
        put :update, {:id => pastevent.to_param, :pastevent => valid_attributes}, valid_session
        response.should redirect_to(pastevent)
      end
    end

    describe "with invalid params" do
      it "assigns the pastevent as @pastevent" do
        pastevent = Pastevent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pastevent.any_instance.stub(:save).and_return(false)
        put :update, {:id => pastevent.to_param, :pastevent => {}}, valid_session
        assigns(:pastevent).should eq(pastevent)
      end

      it "re-renders the 'edit' template" do
        pastevent = Pastevent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pastevent.any_instance.stub(:save).and_return(false)
        put :update, {:id => pastevent.to_param, :pastevent => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pastevent" do
      pastevent = Pastevent.create! valid_attributes
      expect {
        delete :destroy, {:id => pastevent.to_param}, valid_session
      }.to change(Pastevent, :count).by(-1)
    end

    it "redirects to the pastevents list" do
      pastevent = Pastevent.create! valid_attributes
      delete :destroy, {:id => pastevent.to_param}, valid_session
      response.should redirect_to(pastevents_url)
    end
  end

end
